---
title: "Getting started with Linux (OS-GEOLive)"
subtitle: "The terminal, R, and Python"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: united
    toc: yes
    toc_depth: 4
    number_sections: true
---

# Today in the morning

Read and do the below described tutorial

# Today's Learning objectives

- Knowing what Linux is (presentation by Allard De Wit)
- Know how to use the **terminal**!!!
- Getting comfortable within OSGEO-Linux environment
    - Launching Rstudio and using Git
    - Running and writing Python script from the QGIS Python Console


# Using the terminal within Linux

## Open the terminal

See the following tutorial for Geeks! (Warning!: Now you are risking to become a Geek or even computer freak yourself)

- http://www.howtogeek.com/140679/beginner-geek-how-to-start-using-the-linux-terminal/
- http://www.howtogeek.com/howto/42980/the-beginners-guide-to-nano-the-linux-command-line-text-editor/
- http://linuxcommand.org/lc3_learning_the_shell.php
Try to install the following program on Linux

Introduction to use the terminal on Mac//very similar commands on OSGEO-Linux

- http://computers.tutsplus.com/tutorials/navigating-the-terminal-a-gentle-introduction--mac-3855
- http://blog.teamtreehouse.com/introduction-to-the-mac-os-x-command-line

# R and Rstudio within Linux

# Python within Linux

- Via QGIS -> Plug-inns -> Python Console
- Choose you own preferred editor for Python scripts
    - Gedit as simple but good text editor
    - Eric
    - Spyder

## More information

- [An overview of terminal commands](http://beginlinux.com/twitter/1094-the-beginners-guide-to-the-ubuntu-terminal)

